const translateCities = {
    'Tokio': '東京',
    'Seul': '서울',
    'Singapur': '新加坡',
    'Manila': '马尼拉',
    'Jakarta': '雅加达',
    'Hong Kong': '香港',
    'Bangkok': 'กรุงเทพมหานคร',
    'Taipei': '台北',
    'Moscu': 'Москва',
    'Cairo': 'القاهرة',
    'Lagos': 'Lagos',
    'Kiev': 'Київ',
    'Ucrania': 'Україна',
    'Polonia': 'Polska',
    'Alemania': 'Deutschland',
    'Arabia Saudita': 'المملكة العربية السعودية',
    'Bagdad': 'بغداد',
    'Bangladesh': 'বাংলাদেশ',
    'Birmania': 'မြန်မာ',
    'Donetsk': 'Донецк',
    'Nanjing': '南京',
    'Nueva Delhi': 'नई दिल्ली',
    'Chennai': 'சென்னை',
    'Qatar': 'قطر',
    'Luxor': 'لوكسور',
    'Marrakech': 'مراكش',
    'Shanghai': '上海',
    'Beijing': '北京',
}

export default translateCities;